module.exports=function(sequelize, dataTypes){
    const Producto = sequelize.define("Producto",{
        id:{
            type:dataTypes.BIGINT(10).UNSIGNED,
            autoIncrement:true,
            primaryKey:true,
            allowNull:false
        },
        nombre:{
            type:dataTypes.STRING(100),
            allowNull:false
        },
        precio:{
            type:dataTypes.DECIMAL(10,2).UNSIGNED,
            allowNull:false
        },
        descuento:{
            type:dataTypes.BIGINT(10).UNSIGNED,
            default:null
        },
        stock:{
            type:dataTypes.BIGINT(10).UNSIGNED,
            default:null
        },
        caracteristicas:{
            type:dataTypes.TEXT,
            default:null
        },
        marca_id:{
            type:dataTypes.BIGINT(10).UNSIGNED,
            allowNull:false,
            foreignkey:true,
        },
        categoria_id:{
            type:dataTypes.BIGINT(10).UNSIGNED,
            allowNull:false,
            foreignKey:true,
        },
        subcategoria_id:{
            type:dataTypes.BIGINT(10).UNSIGNED,
            allowNull:false,
            foreignKey:true,
        },
        estado_id:{
            type:dataTypes.BIGINT(10).UNSIGNED,
            allowNull:false,
            foreignKey:true,
        }
    },{
        createdAt:"created_at",
        updatedAt:"updated_at",
        deletedAt:"deleted_at",
        tableName:"productos",
        paranoid: true
    })

    Producto.associate= function(models){
        Producto.hasMany(models.Calificacion,{
            as:"calificaciones",
            foreignKey:"producto_id"
        })
        Producto.hasMany(models.Imagen,{
            as:"imagenes",
            foreignKey:"producto_id"
        })
        Producto.hasMany(models.Carrito,{
            as:"carritos",
            foreignKey:"producto_id",
        })
        Producto.belongsTo(models.Marca,{
            as:"marcas",
            foreignKey:"marca_id"
        })
        Producto.belongsTo(models.Categoria,{
            as:"categorias",
            foreignKey:"categoria_id"
        })
        Producto.belongsTo(models.Subcategoria,{
            as:"subcategorias",
            foreignKey:"subcategoria_id"
        })
        Producto.belongsTo(models.Estado,{
            as:"estados",
            foreignKey:"estado_id"
        })
        Producto.belongsToMany(models.Usuario,{
            as:"carrito",
            through:"carrito_de_compras",
            foreignKey:"producto_id",
            otherKey:"usuario_id",
            timestamps:false
        })
        Producto.belongsToMany(models.Usuario,{
            as:"favoritos",
            through:"favoritos_de_usuarios",
            foreignKey:"producto_id",
            otherKey:"usuario_id",
            timestamps:false
        })
        Producto.belongsToMany(models.Color,{
            as:"colores",
            through:"producto_color",
            foreignKey:"producto_id",
            otherKey:"color_id",
            timestamps:false
        })
        Producto.belongsToMany(models.Tamano,{
            as:"tamanos",
            through:"producto_tamano",
            foreignKey:"producto_id",
            otherKey:"tamano_id",
            timestamps:false
        })
        
        
    }

    return Producto
}